---
- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/Privatespace"
  roles:
    # Common roles
    - role: webarchitect609.jet_brains_toolbox
      become: true
      toolbox_install_for_user: "{{ lookup('env', 'USER') }}"
      toolbox_install_dir: /usr/local/bin
      tags: [install, core]
    - role: haxorof.docker_ce
      become: true
      docker_users: ["{{ lookup('env', 'USER') }}"]
      docker_compose: true
      tags: [install, core]
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags: [install, core]
  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
