---
- name: Installing stow
  apt: name=stow
  tags: [install, dotfiles, stow]
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: https://github.com/bmihovski/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/Privatespace/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: master
  tags: [install, dotfiles, stow]
- name: Stow dotfiles
  shell: cd $HOME/Privatespace/.dotfiles && ./ubuntu && ./process decrypt
  tags: [install, dotfiles, stow]
