---
- name: Git setup http proxy
  git_config:
    name: http.proxy
    scope: global
    value: http://127.0.0.1:48157
  tags: [git-vdi]
- name: Git setup https proxy
  git_config:
    name: https.proxy
    scope: global
    value: http://127.0.0.1:48157
  tags: [git-vdi]
